Idaho Comp Changes and PID control
TeamLineBreak/Robotics pull request #16
Opened 2022-04-01 14:09 UTC by TeamLineBreak

2022-04-01 18:33 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/commands/BlankCommand.java
> +    return false;
Why was this change made?

2022-04-01 18:33 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/commands/DriveCommand.java
> +		return false;
Again, why was this change made?

2022-04-01 18:36 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/commands/PrepForSwitchToClimb.java
> +        climbingSub.setStationaryVerticalPos(1.0);
All good, but we should use the variable that is tuned to .95 instead of 1?

2022-04-01 20:29 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/commands/BlankCommand.java
> +    return false;
Change was made because we are using `.withTimeout()` in the AutonomousGroup.java

2022-04-04 00:59 UTC, Coderdude112 requested changes

2022-04-04 01:11 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/PrepForSwitchToClimb.java
> +        return false;
Beacuse, the command is now a hold command, the button it is bound to be `.whenHeld()` now rather than `.whenPressed()`

2022-04-04 01:11 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/StationaryVerticalMove.java
> +    private double clamp(double value, double min, double max) {
I was going to, but didnt have time at the comp

2022-04-04 01:11 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/StationaryVerticalMove.java
> +        if (!(OI.getInstance().isClimbingEnabled())) { // Ensure climbing is enabled before moving any arms
we shouldnt be, will remove

2022-04-04 01:11 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/PrepForSwitchToClimb.java
> +        climbingSub.setStationaryVerticalPos(1.0);
yes

2022-04-04 01:15 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/NonStationaryVerticalMove.java
> +        // climbingSub.setNonStationaryVerticalPos(climbingSub.getNonStationaryVerticalPos() + (moveUp ? .5 : -.5));
this is commented bc those methods did not i for a while

2022-04-04 01:16 UTC, GiGodN commented on 2022/src/main/java/frc/robot/commands/AutonomusGoup.java
> +				new DriveCommand(0, 0, 0) // REQUIRED: Force the robot to stop when there are no more auto commands to run
lets wait until we know what we will be mounting for the next comp

2022-04-04 01:31 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/commands/AutonomusGoup.java
> +				new DriveCommand(0, 0, 0) // REQUIRED: Force the robot to stop when there are no more auto commands to run
Sounds good, we should create an issue

2022-04-06 13:52 UTC, Coderdude112 commented on 2022/src/main/java/frc/robot/wrappers/PIDMotorWrapper.java
> + * I am not willing to document this until the comps are over, dont talk about it
Done

2022-04-06 13:59 UTC, Coderdude112 approved these changes
Made a small change, everything else looks good.

2022-04-06 13:59 UTC, merged